# Install dependencies only when needed
FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./ 
RUN npm install --frozen-lockfile --legacy-peer-deps -f

# Rebuild the source code only when needed
FROM node:20-alpine AS builder
WORKDIR /app
COPY . .
COPY --from=deps /app/node_modules ./node_modules
RUN npm run build

# Production image, minimal setup
FROM node:20-alpine AS runner
WORKDIR /app

# Ensure the app uses production mode
ENV NODE_ENV=production

# Copy standalone output from builder
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# Copy the public folder for serving static assets
COPY --from=builder /app/public ./public

EXPOSE ${PORT}

CMD ["node", "server.js"]
