export const QUERY_KEYS = {
  POSTS: 'POSTS',
  FEATURED_ARTICLE: 'FEATURED_ARTICLE',
  RECENT: 'RECENT',
  RELATE: 'RELATE',
  NEWSSOURCE: 'NEWSSOURCE',
  TAG: 'TAG',
  SEARCH: 'SEARCH',
  EVENT: 'EVENT',
  EVENT_ALL: 'EVENT_ALL',
  HIGHLIGHT: 'HIGHLIGHT',
  MOST_VIEWED: 'MOST_VIEWED',
};
