sonar.projectKey=mobile_react-native_base_AYqHu7WBiUopT_PhOKji
sonar.qualitygate.wait=true
sonar.projectName=Base Mobile
sonar.projectVersion=1.0

sonar.sources=android,ios,src

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/*.java,**/*.test.*

## Flex Specific Properties

# retrieve code coverage data from the Cobertura report
sonar.flex.cobertura.reportPath=coverage-report/coverage-cobertua-flex.xml

# PL/I Specific Properties
sonar.pli.marginLeft=2
sonar.pli.marginRight=0
